[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contract = "9EP3RUfKCHk9ERWwTKd2k2QxQAJU4agBQVeND5DSo41c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kritex/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
